package com.dawgs.marketplace.model;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for the Listing model class.
 * These tests check that the getters/setters work correctly and
 * that default values are set properly. No Spring context needed here.
 */
public class ListingModelTest {

    @Test
    void testCreateListingAndSetFields() {
        Listing listing = new Listing();
        listing.setTitle("MacBook Pro 2021");
        listing.setDescription("Barely used, great condition");
        listing.setPrice(800.00);
        listing.setContactInfo("student@uw.edu");

        assertEquals("MacBook Pro 2021", listing.getTitle());
        assertEquals("Barely used, great condition", listing.getDescription());
        assertEquals(800.00, listing.getPrice());
        assertEquals("student@uw.edu", listing.getContactInfo());
    }

    @Test
    void testNewListingDefaultSoldIsFalse() {
        // A brand-new listing should never start out as sold
        Listing listing = new Listing();
        assertFalse(listing.isSold(), "New listing should not be marked as sold by default");
    }

    @Test
    void testMarkListingAsSold() {
        Listing listing = new Listing();
        listing.setSold(true);
        assertTrue(listing.isSold(), "Listing should be sold after setting sold=true");
    }

    @Test
    void testUnmarkListingAsSold() {
        Listing listing = new Listing();
        listing.setSold(true);
        listing.setSold(false);
        assertFalse(listing.isSold(), "Should be able to unmark a listing as sold");
    }

    @Test
    void testSetPriceToZeroForFreeItem() {
        // Price of 0 means the item is free - should be valid
        Listing listing = new Listing();
        listing.setPrice(0.0);
        assertEquals(0.0, listing.getPrice(), 0.001, "Free items (price=0) should be allowed");
    }

    @Test
    void testSetHighPrice() {
        Listing listing = new Listing();
        listing.setPrice(9999.99);
        assertEquals(9999.99, listing.getPrice(), 0.001);
    }

    @Test
    void testSetAndGetOwnerId() {
        Listing listing = new Listing();
        listing.setOwnerId("google-user-id-123456789");
        assertEquals("google-user-id-123456789", listing.getOwnerId());
    }

    @Test
    void testSetAndGetImageUrl() {
        Listing listing = new Listing();
        listing.setImageUrl("https://res.cloudinary.com/demo/image/upload/sample.jpg");
        assertEquals("https://res.cloudinary.com/demo/image/upload/sample.jpg", listing.getImageUrl());
    }

    @Test
    void testImageUrlIsNullByDefault() {
        // imageUrl is optional - not all sellers have a photo
        Listing listing = new Listing();
        assertNull(listing.getImageUrl(), "imageUrl should be null before it is set");
    }

    @Test
    void testOwnerIdIsNullByDefault() {
        // ownerId is set by the controller, not in the model constructor
        Listing listing = new Listing();
        assertNull(listing.getOwnerId());
    }

    @Test
    void testIdIsNullBeforePersist() {
        // The UUID id is generated by the database, so it's null until we save
        Listing listing = new Listing();
        assertNull(listing.getId(), "Id should be null before the entity is saved to the database");
    }

    @Test
    void testCreatedAtIsNullBeforePersist() {
        // createdAt is set by the @PrePersist hook, so it should be null before saving
        Listing listing = new Listing();
        assertNull(listing.getCreatedAt());
    }

    @Test
    void testUpdateListingTitle() {
        Listing listing = new Listing();
        listing.setTitle("Old Laptop");
        listing.setTitle("New Laptop");
        assertEquals("New Laptop", listing.getTitle());
    }

    @Test
    void testUpdateListingPrice() {
        Listing listing = new Listing();
        listing.setPrice(100.0);
        listing.setPrice(85.0); // seller lowered the price
        assertEquals(85.0, listing.getPrice(), 0.001);
    }

    @Test
    void testListingWithAllFieldsSet() {
        // Simulate creating a full listing like a real user would post
        Listing listing = new Listing();
        listing.setTitle("Calculus Textbook");
        listing.setDescription("MATH 124 textbook, 8th edition. Some highlighting but still readable.");
        listing.setPrice(40.00);
        listing.setImageUrl("https://cloudinary.com/book.jpg");
        listing.setOwnerId("user-abc-123");
        listing.setContactInfo("seller@uw.edu");
        listing.setSold(false);

        assertAll(
            () -> assertEquals("Calculus Textbook", listing.getTitle()),
            () -> assertEquals("MATH 124 textbook, 8th edition. Some highlighting but still readable.", listing.getDescription()),
            () -> assertEquals(40.00, listing.getPrice(), 0.001),
            () -> assertEquals("https://cloudinary.com/book.jpg", listing.getImageUrl()),
            () -> assertEquals("user-abc-123", listing.getOwnerId()),
            () -> assertEquals("seller@uw.edu", listing.getContactInfo()),
            () -> assertFalse(listing.isSold())
        );
    }
}
